server:
  port: 8090
spring:
  application:
    description: CSV Manager
    version: 0.0.1
    name: csvmanager
  datasource:
    url: jdbc:mysql://localhost:3306/csv-importer?useSSL=false&allowPublicKeyRetrieval=true
    username: csvimporter
    password: csvimporter
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: validate # no borrar las tablas
      ddl-auto: none #create-drop # cada ejecución se borra las tablas y se crean nuevamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/

application:
  csv:
    parser: apache-commons-csv

debug: false

logging:
  level:
    root: INFO
    liquibase: INFO